workspace:
  base: /go
  path: src/github.com/udistrital/${DRONE_REPO}
  when:
      branch:
      - develop
      - release/*
      - master

kind: pipeline
name: oas_api_ci

steps:
  - name: check_readme
    image: jjvargass/qa_develoment:latest
    commands:
    - python /app/check_readme.py
    when:
      branch:
      - develop
      - feature/*
      - release/*
      event:
      - push

  - name: check_branch
    image: jjvargass/qa_develoment:latest
    commands:
    - python /app/check_branch.py -H ${DRONE_GIT_HTTP_URL}
    when:
      branch:
      - develop
      - feature/*
      - release/*
      event:
      - push

  - name: check_commits
    image: jjvargass/qa_develoment:latest
    commands:
    - python /app/check_commits.py
    when:
      branch:
      - develop
      - feature/*
      - release/*
      event:
      - push

  - name: run_sonar_scanner
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: SONAR_HOST
      sonar_token:
        from_secret: SONAR_TOKEN

  - name: publish_to_ecr_release
    image: plugins/ecr
    settings:
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region:
        from_secret: AWS_REGION
      repo: ${DRONE_REPO}
      tags:
        - ${DRONE_COMMIT:0:7}
        - release
    when:
      branch:
      - release/*
      event:
      - push

  - name: publish_to_ecr_master
    image: plugins/ecr
    settings:
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region:
        from_secret: AWS_REGION
      repo: ${DRONE_REPO}
      tags:
        - ${DRONE_COMMIT:0:7}
        - latest
    when:
      branch:
      - master
      event:
      - push

  - name: update_ecs_service
    image: amazon/aws-cli:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION:
        from_secret: AWS_REGION
    commands:
    - case ${DRONE_BRANCH} in
      master)
      SUFFIX=prod
      CLUSTER=oas
        ;;
      *)
      SUFFIX=test
      CLUSTER=test
        ;;
      esac
    - aws ecs update-service
      --cluster $${CLUSTER}
      --service $${DRONE_REPO_NAME}_$${SUFFIX}
      --force-new-deployment
      --query "service.deployments[0].id"
    when:
      branch:
        - release/*
        - master
      event:
        - push
