basePath: /v1
consumes:
- application/json
definitions:
  Metadata_properties:
    properties:
      dc:description:
        type: string
      dc:language:
        type: string
      dc:publisher:
        type: string
      dc:rights:
        type: string
      dc:source:
        type: string
      dc:title:
        type: string
      nxtag:tags:
        items:
          $ref: '#/definitions/nuxeo_tags'
        type: array
    type: object
  Nuxeo_dublin_core_metadata:
    properties:
      properties:
        $ref: '#/definitions/Metadata_properties'
    type: object
  documentos_crud_metadata:
    properties:
      dato_a:
        type: string
      dato_b:
        type: string
      dato_n:
        type: string
    type: object
  nuxeo_tags:
    properties:
      label:
        type: string
      username:
        type: string
    type: object
  upload_resquest:
    properties:
      IdTipoDocumento:
        type: integer
      descripcion:
        type: string
      file:
        type: string
      metadatos:
        $ref: '#/definitions/documentos_crud_metadata'
      nombre:
        type: string
    type: object
info:
  description: Api mid para la autenticacion de documentos en Nuxeo
  title: gestor_documental_mid
  version: '1.0'
paths:
  /:
    get:
      operationId: get_healthcheck
      responses:
        '200':
          description: Success
        '500':
          description: Nuxeo error
      tags:
      - /
  /document/firma_electronica:
    post:
      operationId: post_firma__electronica
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/upload_resquest'
          type: array
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '500':
          description: Nuxeo error
      tags:
      - document
  /document/store_document:
    post:
      operationId: post_store__document
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/upload_resquest'
          type: array
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '500':
          description: Nuxeo error
      tags:
      - document
  /document/upload:
    post:
      operationId: post_upload
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/upload_resquest'
          type: array
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '500':
          description: Nuxeo error
      tags:
      - document
  /document/{uid}:
    delete:
      operationId: delete_document_/document/<string:uid>
      parameters:
      - default: false
        description: Conservar documento en Nuxeo?
        in: query
        name: versionar
        type: boolean
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Nuxeo error
      tags:
      - document
    get:
      operationId: get_document_/document/<string:uid>
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Nuxeo error
      tags:
      - document
    parameters:
    - description: UID del documento generado en Nuxeo
      in: path
      name: uid
      required: true
      type: string
  /document/{uid}/metadata:
    parameters:
    - description: UID del documento generado en Nuxeo
      in: path
      name: uid
      required: true
      type: string
    post:
      operationId: post_metadata_/document/<string:uid>/metadata
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/Nuxeo_dublin_core_metadata'
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Nuxeo error
      tags:
      - document
produces:
- application/json
responses:
  MaskError:
    description: When any error occurs on mask
  ParseError:
    description: When a mask can't be parsed
swagger: '2.0'
tags:
- description: Nuxeo service Healthcheck
  name: /
- description: Nuxeo document operations
  name: document
