basePath: /v1
consumes:
- application/json
definitions:
  Metadata_properties:
    properties:
      dc:description:
        type: string
      dc:language:
        type: string
      dc:publisher:
        type: string
      dc:rights:
        type: string
      dc:source:
        type: string
      dc:title:
        type: string
      nxtag:tags:
        items:
          $ref: '#/definitions/nuxeo_tags'
        type: array
    type: object
  Nuxeo_dublin_core_metadata:
    properties:
      properties:
        $ref: '#/definitions/Metadata_properties'
    type: object
  documentos_crud_metadata:
    properties:
      dato_a:
        type: string
      dato_b:
        type: string
      dato_n:
        type: string
    type: object
  nuxeo_tags:
    properties:
      label:
        type: string
      username:
        type: string
    type: object
  upload_resquest:
    properties:
      IdTipoDocumento:
        type: integer
      descripcion:
        type: string
      file:
        type: string
      metadatos:
        $ref: '#/definitions/documentos_crud_metadata'
      nombre:
        type: string
    type: object
info:
  description: Api mid para la autenticacion de documentos en Nuxeo
  title: gestor_documental_mid
  version: '1.0'
paths:
  /document/:
    get:
      description: "Parameters\n----------\nRequest : ?query=params&limit=values&offset=values\n\
        \    query: usa la misma métodologia de consulta que en apis beego, e.j: ?query=Nombre:doc...\n\
        \            - para lista de documentos use parametro__in:valor1|valor2|...|valorn\
        \ e.j: Id__in:2|3|4\n            - puede anida querys separandolos por ';'\
        \ si requiere varias consultas con distintos parametros, e.j: Id:2;Nombre:contrato\n\
        \    limit & offset: son opcionales, limit defecto a 10 y offset a 0\n   \
        \ - si anida querys, y usa offset o limit debe haber un valor para cada query\
        \ separados por ';' o ','\n    - e.j: ?query=Id:2;Nombre:contrato&limit=1;10&offset=0;5\n\
        \    Nota: procure evitar uso de 0 o -1 para limit, si no conoce la cantidad\
        \ de documentos.\n\nReturns\n-------\nResponse : json\n    Respuesta con Status,\
        \ Code, Data y Errors en formato json"
      operationId: get_document_get_all_/document/
      responses:
        '200':
          description: Success
        '206':
          description: Partial Content
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Nuxeo error
      summary: Permite consultar listado de documentos, usando como contexto de busqueda
        la tabla documento de documentos_crud
      tags:
      - document
    parameters:
    - description: Query similar to documentos_crud
      in: query
      name: query
      type: string
    - description: limit similar a documentos_crud
      in: query
      name: limit
      type: string
    - description: offset similar a documentos_crud
      in: query
      name: offset
      type: string
  /document/firma_electronica:
    post:
      description: "Parameters\n----------\nrequest : json\n    Json Body {Document},\
        \ Documento que será subido a nuxeo y firmantes\n\nReturns\n-------\nResponse\n\
        \    Respuesta con cuerpo, status y en formato json"
      operationId: post_document_post_firma_electronica
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/upload_resquest'
          type: array
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '500':
          description: Nuxeo error
      summary: Permite subir documento pdf y ser firmado electrónicamente
      tags:
      - document
  /document/store_document:
    post:
      description: "Parameters\n----------\nrequest : json\n    Json Body {Document},\
        \ Documento que será subido a nuxeo\n\nReturns\n-------\nResponse\n    Respuesta\
        \ con cuerpo, status y en formato json"
      operationId: post_document_post_store_document
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/upload_resquest'
          type: array
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '500':
          description: Nuxeo error
      summary: Permite subir documento
      tags:
      - document
  /document/upload:
    post:
      description: "Parameters\n----------\nrequest : json\n    Json Body {Document},\
        \ Documento que será subido a nuxeo\n\nReturns\n-------\nResponse\n    Respuesta\
        \ con cuerpo, status y en formato json"
      operationId: post_document_post
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/upload_resquest'
          type: array
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '500':
          description: Nuxeo error
      summary: Permite subir documento
      tags:
      - document
  /document/uploadAnyFormat:
    post:
      description: "Parameters\n----------\nrequest : json\n    Json Body {Document},\
        \ Documento que será subido a nuxeo\n\nReturns\n-------\nResponse\n    Respuesta\
        \ con cuerpo, status y en formato json"
      operationId: post_document_post_any_format
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/upload_resquest'
          type: array
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '500':
          description: Nuxeo error
      summary: Permite subir cualquier tipo de documento, de acuerdo a la extensión
        de su nombre
      tags:
      - document
  /document/verify:
    post:
      description: "Parameters\n----------\nrequest : json\n    Json Body {firma},\
        \ firma electronica encriptada con el id\n\nReturns\n-------\nResponse\n \
        \   Respuesta con cuerpo, status y en formato json"
      operationId: post_document_post_verify
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/upload_resquest'
          type: array
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '500':
          description: Nuxeo error
      summary: permite verificar la firma electronica de un documento
      tags:
      - document
  /document/{uid}:
    delete:
      description: "Parameters\n----------\nrequest : uid, versionar\n\nReturns\n\
        -------\nResponse\n    Respuesta con cuerpo, status y en formato json"
      operationId: delete_document_get_one__delete_one_/document/<string:uid>
      parameters:
      - default: false
        description: Conservar documento en Nuxeo?
        in: query
        name: versionar
        type: boolean
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Nuxeo error
      summary: Permite borrar documento por uid
      tags:
      - document
    get:
      description: "Parameters\n----------\nrequest : uid\n\nReturns\n-------\nResponse\n\
        \    Respuesta con cuerpo, status y en formato json"
      operationId: get_document_get_one__delete_one_/document/<string:uid>
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Nuxeo error
      summary: Permite consultar documento por uid
      tags:
      - document
    parameters:
    - description: UID del documento generado en Nuxeo
      in: path
      name: uid
      required: true
      type: string
  /document/{uid}/metadata:
    parameters:
    - description: UID del documento generado en Nuxeo
      in: path
      name: uid
      required: true
      type: string
    post:
      description: "Parameters\n----------\nrequest : uid, json\n    uid del documento\n\
        \    Json Body {Metadata}, metadata\n\nReturns\n-------\nResponse\n    Respuesta\
        \ con cuerpo, status y en formato json"
      operationId: post_document_post_metadata_/document/<string:uid>/metadata
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/Nuxeo_dublin_core_metadata'
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Nuxeo error
      summary: Permite cargar metadata relacionada a documento
      tags:
      - document
produces:
- application/json
responses:
  MaskError:
    description: When any error occurs on mask
  ParseError:
    description: When a mask can't be parsed
swagger: '2.0'
tags:
- description: Nuxeo document operations
  name: document
